version: "3.7"

services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    
    ports:
      # Evita conflito com a app local (docker-compose.yml usa 8088)
      - "8091:80"
    
    environment:
      - PMA_HOST=172.17.0.1
      - PMA_PORT=3308
      - PMA_USER=root
      - PMA_PASSWORD=root_password_2025
      - UPLOAD_LIMIT=50M
      - MEMORY_LIMIT=512M
