ALTER TABLE `ingredients`
  ADD COLUMN `cost` DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER `name`,
  ADD COLUMN `sale_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER `cost`,
  ADD COLUMN `unit` VARCHAR(30) NOT NULL DEFAULT '' AFTER `sale_price`,
  ADD COLUMN `unit_value` DECIMAL(10,3) NOT NULL DEFAULT 1.000 AFTER `unit`;
